{ collisionCount : (Optional (Integer))
, conditions : (Optional (List ./io.k8s.api.apps.v1.DaemonSetCondition.dhall))
, currentNumberScheduled : (Integer)
, desiredNumberScheduled : (Integer)
, numberAvailable : (Optional (Integer))
, numberMisscheduled : (Integer)
, numberReady : (Integer)
, numberUnavailable : (Optional (Integer))
, observedGeneration : (Optional (Integer))
, updatedNumberScheduled : (Optional (Integer))
}
