{ collisionCount : (Optional (Natural))
, conditions : (Optional (List ./io.k8s.api.apps.v1.DaemonSetCondition.dhall))
, currentNumberScheduled : (Natural)
, desiredNumberScheduled : (Natural)
, numberAvailable : (Optional (Natural))
, numberMisscheduled : (Natural)
, numberReady : (Natural)
, numberUnavailable : (Optional (Natural))
, observedGeneration : (Optional (Natural))
, updatedNumberScheduled : (Optional (Natural))
}
