{ collisionCount : (Optional (Integer))
, conditions : (Optional (List ./io.k8s.api.apps.v1beta1.StatefulSetCondition.dhall))
, currentReplicas : (Optional (Integer))
, currentRevision : (Optional (Text))
, observedGeneration : (Optional (Integer))
, readyReplicas : (Optional (Integer))
, replicas : (Integer)
, updateRevision : (Optional (Text))
, updatedReplicas : (Optional (Integer))
}
