{ chapAuthDiscovery : (Optional (Bool))
, chapAuthSession : (Optional (Bool))
, fsType : (Optional (Text))
, initiatorName : (Optional (Text))
, iqn : (Text)
, iscsiInterface : (Optional (Text))
, lun : (Natural)
, portals : (Optional (List Text))
, readOnly : (Optional (Bool))
, secretRef : (Optional (./io.k8s.api.core.v1.LocalObjectReference.dhall))
, targetPortal : (Text)
}
