{ categories : (Optional (List Text))
, group : (Optional (Text))
, kind : (Text)
, name : (Text)
, namespaced : (Bool)
, shortNames : (Optional (List Text))
, singularName : (Text)
, verbs : (List Text)
, version : (Optional (Text))
}
